version: '3'
services:
  api:
    container_name: "RatingAtcoder"
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./code:/usr/src
    tty: true